name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - run: git config --global user.name 'Version Bump'
      - run: git config --global user.email 'vb@githubaction.in'
      - run: npm version patch -m "Verision bumped to %s"
      - run: git push